language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
python:
  - "2.7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
